### ISSUE TITLE
Cannot load dependencies when installing (NumPy not available when `get_numpy_include_path` called)

### ISSUE THREAD

**Issue by josePhoenix** [astropy/package-template#107]
Typically when starting work on a new project, I create a fresh `virtualenv`, clone the project repo, and use `python setup.py develop` or `pip install -e .` to set up a locally editable copy. I tried this with [mperrin/webbpsf](https://github.com/mperrin/webbpsf) and immediately ran into trouble. It looks like the issue lies within the package template, and I can reproduce it trying to install the template package.

```
$ git clone https://github.com/astropy/package-template.git
$ mkvirtualenv astropytemplate
$ cd package-template
$ pip install -e .
[ ... parts omitted ... ]
Installing collected packages: packagename, numpy
  Running setup.py develop for packagename
[ ... ]
running build_ext

Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/Users/jlong/GitHub/package-template/setup.py", line 108, in <module>

    **package_info

  File "/Users/jlong/homebrew/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup

    dist.run_commands()

  File "/Users/jlong/homebrew/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands

    self.run_command(cmd)

  File "/Users/jlong/homebrew/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "/Users/jlong/.virtualenvs/webbpsf/lib/python2.7/site-packages/setuptools/command/develop.py", line 27, in run

    self.install_for_development()

  File "/Users/jlong/.virtualenvs/webbpsf/lib/python2.7/site-packages/setuptools/command/develop.py", line 114, in install_for_development

    self.run_command('build_ext')

  File "/Users/jlong/homebrew/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command

    self.distribution.run_command(command)

  File "/Users/jlong/homebrew/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "/Users/jlong/GitHub/package-template/astropy_helpers/astropy_helpers/setup_helpers.py", line 518, in run

    np_include = get_numpy_include_path()

  File "/Users/jlong/GitHub/package-template/astropy_helpers/astropy_helpers/setup_helpers.py", line 1309, in get_numpy_include_path

    import numpy

ImportError: No module named numpy
```

(Notably, this is _after_ downloading and building NumPy apparently successfully, but perhaps not installing.)

Full output in Gist: https://gist.github.com/josePhoenix/2b52ed30fc53779ad097

**Comment by drdavella** [comment]
This has been recorded in https://github.com/astropy/astropy-helpers/issues/402 and should be resolved by https://github.com/astropy/astropy-helpers/pull/404, so it can be closed here.
