### ISSUE TITLE
edit_on_github doesn't work out of the box

### ISSUE THREAD

**Issue by cdeil** [astropy/package-template#125]
During handling of the above exception, another exception occurred:

I just followed the instructions [here](http://astropy.readthedocs.org/en/latest/development/affiliated-packages.html?packagename=astroplan) to set up a new Astropy-affiliated package [here](https://github.com/astroplanners/astroplan).

I get this error from `python setup.py build_sphinx` if I set `edit_on_github = True` in `setup.cfg`:
```
Traceback (most recent call last):
  File "<stdin>", line 28, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sphinx/application.py", line 143, in __init__
    self.setup_extension(extension)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sphinx/application.py", line 433, in setup_extension
    err)
sphinx.errors.ExtensionError: Could not import extension astropy.sphinx.ext.edit_on_github (exception: No module named 'astropy.sphinx')
Sphinx Documentation subprocess failed with return code 1
```
Maybe this import has to be updated to point to `astropy-helpers`?

**Comment by cdeil** [comment]
This is a duplicate of #119 .
