### ISSUE TITLE
jinja2.exceptions.TemplateNotFound: autosummary/base.rst

### ISSUE THREAD

**Issue by cdeil** [astropy/package-template#126]
I'm getting this Sphinx error from https://github.com/astroplanners/astroplan/commit/e538cc4b9910844916250ca792ecfae8efa681e6 .

Running `python setup.py build_sphinx` fails twice complaining `jinja2.exceptions.TemplateNotFound: autosummary/base.rst` and then, without any changes to code / docs, succeeds on the third re-run!???
```
eduroam-3-163:astroplan deil$ git clean -fdx
Removing .coverage
Removing .idea/
Removing __pycache__/
Removing astroplan.egg-info/
Removing astroplan/__pycache__/
Removing astroplan/tests/__pycache__/
Removing astroplan/version.py
Removing build/
Removing dist/
Removing docs/_build/
Removing docs/_static/
Removing docs/api/
Removing htmlcov/
eduroam-3-163:astroplan deil$ python setup.py build_sphinx
Freezing version number to astroplan/version.py
running build_sphinx
creating /Users/deil/code/astroplan/docs/_build
creating /Users/deil/code/astroplan/docs/_build/doctrees
creating /Users/deil/code/astroplan/docs/_build/html
creating /Users/deil/code/astroplan/docs/_static
running build
running build_py
creating build
creating build/lib.macosx-10.10-x86_64-3.4
creating build/lib.macosx-10.10-x86_64-3.4/astroplan
copying astroplan/__init__.py -> build/lib.macosx-10.10-x86_64-3.4/astroplan
copying astroplan/_astropy_init.py -> build/lib.macosx-10.10-x86_64-3.4/astroplan
copying astroplan/conftest.py -> build/lib.macosx-10.10-x86_64-3.4/astroplan
copying astroplan/utils.py -> build/lib.macosx-10.10-x86_64-3.4/astroplan
copying astroplan/version.py -> build/lib.macosx-10.10-x86_64-3.4/astroplan
creating build/lib.macosx-10.10-x86_64-3.4/astroplan/tests
copying astroplan/tests/__init__.py -> build/lib.macosx-10.10-x86_64-3.4/astroplan/tests
copying astroplan/tests/setup_package.py -> build/lib.macosx-10.10-x86_64-3.4/astroplan/tests
copying astroplan/tests/test_utils.py -> build/lib.macosx-10.10-x86_64-3.4/astroplan/tests
copying astroplan/tests/coveragerc -> build/lib.macosx-10.10-x86_64-3.4/astroplan/tests
Running Sphinx v1.3.1
loading pickled environment... not yet created
loading intersphinx inventory from http://docs.python.org/objects.inv...
loading intersphinx inventory from /Users/deil/code/astroplan/astropy_helpers/astropy_helpers/sphinx/local/python3links.inv...
loading intersphinx inventory from http://docs.scipy.org/doc/scipy/reference/objects.inv...
loading intersphinx inventory from http://matplotlib.org/objects.inv...
loading intersphinx inventory from http://docs.scipy.org/doc/numpy/objects.inv...
loading intersphinx inventory from http://astroquery.readthedocs.org/en/latest/objects.inv...
loading intersphinx inventory from http://docs.astropy.org/en/stable/objects.inv...
[autosummary] generating autosummary for: getting_started/index.rst, index.rst
[automodsumm] index.rst: found 2 automodsumm entries to generate
Traceback (most recent call last):
  File "/Users/deil/code/astroplan/astropy_helpers/astropy_helpers/sphinx/ext/automodsumm.py", line 472, in generate_automodsumm_docs
    template = template_env.get_template(tmplstr % doc.objtype)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sphinx/jinja2glue.py", line 159, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: autosummary/function.rst

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 28, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sphinx/application.py", line 188, in __init__
    self._init_builder(buildername)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sphinx/application.py", line 250, in _init_builder
    self.emit('builder-inited')
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sphinx/application.py", line 497, in emit
    results.append(callback(self, *args))
  File "/Users/deil/code/astroplan/astropy_helpers/astropy_helpers/sphinx/ext/automodsumm.py", line 253, in process_automodsumm_generation
    base_path=app.srcdir)
  File "/Users/deil/code/astroplan/astropy_helpers/astropy_helpers/sphinx/ext/automodsumm.py", line 474, in generate_automodsumm_docs
    template = template_env.get_template(tmplstr % 'base')
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sphinx/jinja2glue.py", line 159, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: autosummary/base.rst
Sphinx Documentation subprocess failed with return code 1
eduroam-3-163:astroplan deil$ python setup.py build_sphinx
running build_sphinx
running build
running build_py
Running Sphinx v1.3.1
loading pickled environment... not yet created
loading intersphinx inventory from http://matplotlib.org/objects.inv...
loading intersphinx inventory from http://astroquery.readthedocs.org/en/latest/objects.inv...
loading intersphinx inventory from http://docs.python.org/objects.inv...
loading intersphinx inventory from http://docs.scipy.org/doc/scipy/reference/objects.inv...
loading intersphinx inventory from /Users/deil/code/astroplan/astropy_helpers/astropy_helpers/sphinx/local/python3links.inv...
loading intersphinx inventory from http://docs.astropy.org/en/stable/objects.inv...
loading intersphinx inventory from http://docs.scipy.org/doc/numpy/objects.inv...
[autosummary] generating autosummary for: api/astroplan.observe.rst, getting_started/index.rst, index.rst
[automodsumm] index.rst: found 2 automodsumm entries to generate
Traceback (most recent call last):
  File "/Users/deil/code/astroplan/astropy_helpers/astropy_helpers/sphinx/ext/automodsumm.py", line 472, in generate_automodsumm_docs
    template = template_env.get_template(tmplstr % doc.objtype)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sphinx/jinja2glue.py", line 159, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: autosummary/function.rst

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 28, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sphinx/application.py", line 188, in __init__
    self._init_builder(buildername)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sphinx/application.py", line 250, in _init_builder
    self.emit('builder-inited')
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sphinx/application.py", line 497, in emit
    results.append(callback(self, *args))
  File "/Users/deil/code/astroplan/astropy_helpers/astropy_helpers/sphinx/ext/automodsumm.py", line 253, in process_automodsumm_generation
    base_path=app.srcdir)
  File "/Users/deil/code/astroplan/astropy_helpers/astropy_helpers/sphinx/ext/automodsumm.py", line 474, in generate_automodsumm_docs
    template = template_env.get_template(tmplstr % 'base')
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sphinx/jinja2glue.py", line 159, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: autosummary/base.rst
Sphinx Documentation subprocess failed with return code 1
eduroam-3-163:astroplan deil$ python setup.py build_sphinx
running build_sphinx
running build
running build_py
Running Sphinx v1.3.1
loading pickled environment... not yet created
loading intersphinx inventory from http://docs.scipy.org/doc/scipy/reference/objects.inv...
loading intersphinx inventory from http://docs.python.org/objects.inv...
loading intersphinx inventory from http://matplotlib.org/objects.inv...
loading intersphinx inventory from http://docs.scipy.org/doc/numpy/objects.inv...
loading intersphinx inventory from /Users/deil/code/astroplan/astropy_helpers/astropy_helpers/sphinx/local/python3links.inv...
loading intersphinx inventory from http://astroquery.readthedocs.org/en/latest/objects.inv...
loading intersphinx inventory from http://docs.astropy.org/en/stable/objects.inv...
[autosummary] generating autosummary for: api/astroplan.observe.rst, api/astroplan.test.rst, getting_started/index.rst, index.rst
[automodsumm] index.rst: found 2 automodsumm entries to generate
building [mo]: all of 0 po files
building [html]: all source files
updating environment: 4 added, 0 changed, 0 removed
reading sources... [100%] index                                                
/Users/deil/code/astroplan/docs/index.rst:50: SEVERE: Title level inconsistent:

Functions
^^^^^^^^^
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index                                                 
<autosummary>:None: WARNING: toctree contains reference to document 'api/astroplan.observe' that doesn't have a title: no link will be generated
<autosummary>:None: WARNING: toctree contains reference to document 'api/astroplan.test' that doesn't have a title: no link will be generated
generating indices... genindex py-modindex
 (0 module code pages)writing additional pages... search
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 3 warnings.
eduroam-3-163:astroplan deil$ find . -name 'base.rst'
./astropy_helpers/astropy_helpers/sphinx/ext/templates/autosummary_core/base.rst
```

**Comment by astrofrog** [comment]
@cdeil - it looks like you forgot to copy over the ``docs/_templates`` directory.

**Comment by cdeil** [comment]
OK, I'll try copying that over soon.

It's currently not mentioned in the guide:
http://astropy.readthedocs.org/en/latest/development/affiliated-packages.html#managing-the-template-files-manually

Also a README file should added.

Also `python setup.py build_sphinx` doesn't currently work for package-template with Sphinx 1.3.
@astrofrog Can you update to the latest astropy-helpers to fix this of should I make a PR?

**Comment by astrofrog** [comment]
@cdeil - I'll try and fix all these today

**Comment by astrofrog** [comment]
See https://github.com/astropy/astropy/pull/3737

**Comment by astrofrog** [comment]
And https://github.com/astropy/package-template/pull/127

**Comment by cdeil** [comment]
@astrofrog - Thanks for fixing these issues.

Indeed, the issue I had for `astroplan` was fixed by adding `docs/_templates`:
https://github.com/astroplanners/astroplan/pull/2
