### ISSUE TITLE
problem running setup.py on a vanilla package_template

### ISSUE THREAD

**Issue by wkerzendorf** [astropy/package-template#15]
I'm running into the following problem at the moment:

`python setup.py build
pkg_resources found
WARNING: Unknown distribution option: 'install_requires' [distutils.dist]
WARNING: Unknown distribution option: 'zip_safe' [distutils.dist]
WARNING: Unknown distribution option: 'use_2to3' [distutils.dist]
running build
running build_py
ERROR: AttributeError: Distribution instance has no attribute 'exclude_package_data' [setuptools.command.build_py]
Traceback (most recent call last):
  File "setup.py", line 109, in <module>
    use_2to3=True
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build.py", line 127, in run
    self.run_command(cmd_name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 971, in run_command
    cmd_obj.ensure_finalized()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/command/build_py.py", line 75, in finalize_options
    self.exclude_package_data = self.distribution.exclude_package_data or {}
AttributeError: Distribution instance has no attribute 'exclude_package_data'`

I'm trying to update macports maybe that will help, but thought it should be documented here.

**Comment by jcfr** [comment]
> AttributeError: Distribution instance has no attribute 'exclude_package_data'

Having faced this issue in a different context, the issue was most likely caused by the fact the installation of `setuptools` was done from its source tree available on https://github.com/pypa/setuptools and was **NOT** `bootstrapped` before being installed.

More details here https://github.com/serge-sans-paille/pythran/issues/489#issuecomment-295459022
