### ISSUE TITLE
Test using egg_info fails when setup_package.py gets fancy

### ISSUE THREAD

**Issue by pllim** [astropy/package-template#164]
I am using the template and have `from astropy.extern inport six` in my `packagename/setup_package.py` and Travis CI failed with the following message when the test is using `egg_info`. Is there a fix for this?

```
python setup.py $SETUP_CMD

Traceback (most recent call last):

  File "setup.py", line 57, in <module>

    cmdclassd = register_commands(PACKAGENAME, VERSION, RELEASE)

  File "/home/travis/build/pllim/synphot/astropy_helpers/astropy_helpers/setup_helpers.py", line 188, in register_commands

    add_command_hooks(registered_commands, srcdir=srcdir)

  File "/home/travis/build/pllim/synphot/astropy_helpers/astropy_helpers/setup_helpers.py", line 221, in add_command_hooks

    for setuppkg in iter_setup_packages(srcdir, packages):

  File "/home/travis/build/pllim/synphot/astropy_helpers/astropy_helpers/setup_helpers.py", line 452, in iter_setup_packages

    name=packagename + '.setup_package')

  File "/home/travis/build/pllim/synphot/astropy_helpers/astropy_helpers/utils.py", line 259, in import_file

    mod = imp.load_module(name, fd, filename, ('.py', mode, 1))

  File "synphot/setup_package.py", line 4, in <module>

    from astropy.extern import six

ImportError: No module named astropy.extern
```

https://travis-ci.org/pllim/synphot/jobs/125673762

**Comment by pllim** [comment]
Fixed in /spacetelescope/synphot_refactor#82 by using my own `six.py` module.

**Comment by embray** [comment]
This just means you don't have `astropy.extern` installed.  You would have to make `astropy` a `setup_requires` of synphot if you expect to be able to use it during synphot's build (though if it's just for the `six` module it's not worth it).

**Comment by astrofrog** [comment]
@pllim - note that ``python setup.py egg_info`` should run without any dependencies installed, so you shouldn't rely on ``six.py`` being available at that point.

**Comment by pllim** [comment]
Thanks.
