### ISSUE TITLE
Error with distutils config ConfigParser again

### ISSUE THREAD

**Issue by cdeil** [astropy/package-template#179]
This issue is related to #169 and #172 .

```
$ python setup.py build_sphinx
running build_sphinx
running build
running build_py
running build_ext
skipping 'packagename/example_c.c' Cython extension (up-to-date)
Running Sphinx v1.4.3
Traceback (most recent call last):
  File "<stdin>", line 28, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sphinx/application.py", line 137, in __init__
    confoverrides or {}, self.tags)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sphinx/config.py", line 291, in __init__
    execfile_(filename, config)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sphinx/util/pycompat.py", line 130, in execfile_
    exec_(code, _globals)
  File "conf.py", line 46, in <module>
    conf = config.ConfigParser()
AttributeError: module 'distutils.config' has no attribute 'ConfigParser'
Sphinx Documentation subprocess failed with return code 1
```

Looks like there's also this place where the import has to be fixed:
https://github.com/astropy/package-template/blame/master/docs/conf.py#L44

I think the fix has to be propagated (manually, sigh) to most affiilated packages?
At least I'm seeing the error with `gammapy` and `astroplan` master since today (not sure why this came up now).

cc @astrofrog @bsipocz @zblz

**Comment by bsipocz** [comment]
@astroplan doesn't yet have the template update merged in (https://github.com/astropy/astroplan/pull/177), so I would say this is expected. 
Have you updated gammapy? If you want I can open a PR for it.

**Comment by cdeil** [comment]
@bsipocz This is another issue that's still present in docs/conf.py in Package-template master

**Comment by bsipocz** [comment]
OK, so this should be fixed with #180.

**Comment by cdeil** [comment]
It does fail in Setup.py in the other repos.

**Comment by bsipocz** [comment]
Great, no mysteries then :)
