### ISSUE TITLE
Initial build of package fails upon first attempt, succeeds on second build

### ISSUE THREAD

**Issue by aphearin** [astropy/package-template#256]
I am using the `package-template` to organize a package I am developing to read, write and analyze large volumes of simulated cosmological data - [umachine_pyio](https://github.com/aphearin/umachine_pyio). After cloning this repo, I find that the first attempt I make build/install the package fails with the Traceback shown below. However, simply calling `python setup.py build` once again in succession works just fine. 

This is not a critical issue since there is a clear workaround. It could also be that there is a simple fix inside `umachine_pyio`. And since the `package-template` is transitioning to be based on `cookiecutter`, maybe this is not a problem that actually needs to be solved regardless. In any case, here is the traceback:

```
Initializing astropy_helpers submodule with: `git submodule update --init -- astropy_helpers`
Traceback (most recent call last):
  File "setup.py", line 80, in <module>
    cmdclassd = register_commands(PACKAGENAME, VERSION, RELEASE)
  File "/Users/aphearin/work/random/0603/umachine_pyio/astropy_helpers/astropy_helpers/setup_helpers.py", line 142, in register_commands
    from .commands.build_sphinx import (AstropyBuildSphinx,
  File "/Users/aphearin/work/random/0603/umachine_pyio/astropy_helpers/astropy_helpers/commands/build_sphinx.py", line 17, in <module>
    from sphinx.setup_command import BuildDoc as SphinxBuildDoc
  File "/Users/aphearin/anaconda/lib/python2.7/site-packages/sphinx/setup_command.py", line 23, in <module>
    from sphinx.application import Sphinx
  File "/Users/aphearin/anaconda/lib/python2.7/site-packages/sphinx/application.py", line 33, in <module>
    from sphinx.environment import BuildEnvironment
  File "/Users/aphearin/anaconda/lib/python2.7/site-packages/sphinx/environment/__init__.py", line 45, in <module>
    from sphinx.util.websupport import is_commentable
  File "/Users/aphearin/anaconda/lib/python2.7/site-packages/sphinx/util/websupport.py", line 11, in <module>
    from sphinxcontrib.websupport.utils import is_commentable  # NOQA
  File "/Users/aphearin/anaconda/lib/python2.7/site-packages/sphinxcontrib/websupport/__init__.py", line 15, in <module>
    from sphinxcontrib.websupport.core import WebSupport  # NOQA
  File "/Users/aphearin/anaconda/lib/python2.7/site-packages/sphinxcontrib/websupport/core.py", line 17, in <module>
    from jinja2 import Environment, FileSystemLoader
  File "/Users/aphearin/anaconda/lib/python2.7/site-packages/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/Users/aphearin/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 15, in <module>
    from jinja2 import nodes
  File "/Users/aphearin/anaconda/lib/python2.7/site-packages/jinja2/nodes.py", line 19, in <module>
    from jinja2.utils import Markup
  File "/Users/aphearin/anaconda/lib/python2.7/site-packages/jinja2/utils.py", line 486, in <module>
    MutableMapping.register(LRUCache)
  File "/Users/aphearin/anaconda/lib/python2.7/abc.py", line 109, in register
    if issubclass(subclass, cls):
  File "/Users/aphearin/anaconda/lib/python2.7/abc.py", line 180, in __subclasscheck__
    if issubclass(subclass, scls):
  File "/Users/aphearin/anaconda/lib/python2.7/site-packages/typing.py", line 1229, in __subclasscheck__
    return super(GenericMeta, self).__subclasscheck__(cls)
TypeError: super() argument 1 must be type, not None
```

**Comment by bsipocz** [comment]
This is the same issue as https://github.com/astropy/astropy-helpers/issues/302, and is a blocker for v2.0 of ``astropy-helpers`` and thus astropy. 

Workaround: I would suggest to uninstall the standalone typing package (and downgrade sphinx to <1.6, as it's a dependency for that).

**Comment by aphearin** [comment]
Ok, thanks for the pointer @bsipocz - no need to leave this issue open then.
