### ISSUE TITLE
Missing "builtins"?

### ISSUE THREAD

**Issue by bmorris3** [astropy/package-template#293]
I'm trying get ReadTheDocs to build successfully for a package built with the package template ([`libra`](https://github.com/bmorris3/libra)), and I'm [consistently getting this error](https://readthedocs.org/projects/libra/builds/6553597/) at the `python setup.py install --force` stage

```
Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    import ah_bootstrap
  File "/home/docs/checkouts/readthedocs.org/user_builds/libra/checkouts/latest/ah_bootstrap.py", line 921, in <module>
    BOOTSTRAPPER = _Bootstrapper.main()
  File "/home/docs/checkouts/readthedocs.org/user_builds/libra/checkouts/latest/ah_bootstrap.py", line 217, in main
    bootstrapper.run()
  File "/home/docs/checkouts/readthedocs.org/user_builds/libra/checkouts/latest/ah_bootstrap.py", line 303, in run
    dist = method()
  File "/home/docs/checkouts/readthedocs.org/user_builds/libra/checkouts/latest/ah_bootstrap.py", line 361, in get_local_directory_dist
    dist = self._directory_import()
  File "/home/docs/checkouts/readthedocs.org/user_builds/libra/checkouts/latest/ah_bootstrap.py", line 458, in _directory_import
    ['egg_info'])
  File "/home/docs/checkouts/readthedocs.org/user_builds/libra/conda/latest/lib/python2.7/site-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/home/docs/checkouts/readthedocs.org/user_builds/libra/conda/latest/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/docs/checkouts/readthedocs.org/user_builds/libra/conda/latest/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/home/docs/checkouts/readthedocs.org/user_builds/libra/conda/latest/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/docs/checkouts/readthedocs.org/user_builds/libra/conda/latest/lib/python2.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/home/docs/checkouts/readthedocs.org/user_builds/libra/conda/latest/lib/python2.7/site-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/home/docs/checkouts/readthedocs.org/user_builds/libra/conda/latest/lib/python2.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/home/docs/checkouts/readthedocs.org/user_builds/libra/conda/latest/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/home/docs/checkouts/readthedocs.org/user_builds/libra/conda/latest/lib/python2.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/home/docs/checkouts/readthedocs.org/user_builds/libra/conda/latest/lib/python2.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/libra/checkouts/latest/astropy_helpers/setup.py", line 7, in <module>
    from astropy_helpers.setup_helpers import register_commands, get_package_info
  File "/home/docs/checkouts/readthedocs.org/user_builds/libra/checkouts/latest/astropy_helpers/astropy_helpers/__init__.py", line 46, in <module>
    import builtins
ImportError: No module named builtins
```

Does this look familiar to anyone?

**Comment by crawfordsm** [comment]
I just ran into this week -- builtins is python 3 only.   So are you building under python 2?  I needed the package to work on python 2 in order to support a legacy system, so what I did was used an older version of astropy_helpers in the software.

**Comment by astrofrog** [comment]
astropy-helpers 3.0rc1 is Python-3 only and is getting picked up if the submodule is not getting checked out - maybe RTD is not checking out the submodule? I think the proper fix is to update ah_bootstrap so that it doesn't update to astropy-helpers 3.x when using Python 2. Discussion here: https://github.com/astropy/astropy-helpers/issues/359

**Comment by astrofrog** [comment]
In terms of short term solutions, you might be able to add ``astropy-helpers<3`` to the ``.rtd-requirements.yml`` file, or start building your docs with Python 3.

**Comment by bsipocz** [comment]
While it's a real helpers issue as @astrofrog mentions above, would that be possible to use python3 for the rtd build even if the package supports python2? Or are these python2 only packages?

**Comment by bmorris3** [comment]
I solved this for my package by adding the following dependency to my `.rtd-environment.yml` file: 
```
    - python=3.4
```
I found that 3.5 and 3.6 each have separate issues presently.
