### ISSUE TITLE
UnsatisfiableError (numpy & matplotlib)

### ISSUE THREAD

**Issue by tcassanelli** [astropy/package-template#300]
There is a new issue will trying to compile the docs on travis. The error is the following,
```
UnsatisfiableError: The following specifications were found to be in conflict:
  - numpy 1.14*
  - numpy stable*
Use "conda info <package>" to see the dependencies for each package.

Installing matplotlib with conda was unsuccessful, using pip instead.
Invalid requirement: 'stable*'

Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/pip/_vendor/packaging/requirements.py", line 92, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1617, in parseString
    raise exc
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1607, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 3376, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1383, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 3164, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pip._vendor.pyparsing.ParseException: Expected stringEnd (at char 6), (line:1, col:7)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/pip/req/req_install.py", line 82, in __init__
    req = Requirement(req)
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/pip/_vendor/packaging/requirements.py", line 96, in __init__
    requirement_string[e.loc:e.loc + 8]))
pip._vendor.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'*'"
```
Looked around and it seems like it is a conda problem. I tested several configurations between matplotlib and numpy versions with no success 🙁.
Perhaps is related to this issue in the [astropy/ci-helpers](https://github.com/astropy/ci-helpers/issues/166).
You can see my output log files [here](https://travis-ci.org/tcassanelli/pyoof/builds) under the "trying to solve the docs" commit.

**Comment by bsipocz** [comment]
Please try to remove numpy from your `CONDA_DEPENDENCIES` list, it's a known limitation with the current setup. https://github.com/astropy/ci-helpers/issues/284

**Comment by bsipocz** [comment]
I'm glad to hear that it solved the issue.
