### ISSUE TITLE
missing 'version.py': indicates -'s have not been substituted with _'s

### ISSUE THREAD

**Issue by keflavich** [astropy/package-template#426]
When I attempt to install a newly created package, I get the following error:
```
$ python setup.py develop
warning: no previously-included files found matching '*.pyc'
warning: no previously-included files found matching '*.o'
no previously-included directories found matching 'build'
Freezing version number to ./casa_notebook_tools/version.py
Traceback (most recent call last):
  File "setup.py", line 26, in <module>
    version = generate_version_py()
  File "/Users/adam/repos/casa-notebook-tools/astropy_helpers/astropy_helpers/version_helpers.py", line 344, in generate_version_py
    with open(version_py, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: './casa_notebook_tools/version.py'
```
I suspect this is a red herring, and the actual problem is that the package is called `casa-notebook-tools`, not `casa_notebook_tools`, but I'm posting the error as is; I'll add updates as I figure this out.

**Comment by pllim** [comment]
Probably irrelevant anymore due to #438 . Please open new issue if you see it again.
